---
stages:
- name: Build Stage
  inputs:
  - type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    build_type: shell
    script: |-
      #!/bin/bash
      # The default Node.js version is 0.10.40
      # To use Node.js 0.12.7, uncomment the following line:
      #export PATH=/opt/IBM/node-v0.12/bin:$PATH
      # To use Node.js 4.2.2, uncomment the following line:
      #export PATH=/opt/IBM/node-v4.2/bin:$PATH
      
      # Build web client
      if [ -d ./webclient ]; then
        pushd .
        cd ./webclient
        echo "-- Installing dependencies..."
        npm install || echo npm-debug.log
        echo "-- Compiling typescript..."
        npm run tsc
        npm run gulp
        # Cleaning up node_modules
        rm -Rf ./node_modules
        popd
      fi
      # if necessary
      #npm install
- name: Deploy Stage
  inputs:
  - type: job
    stage: Build Stage
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: Deploy
    type: deployer
    target:
       organization: ${CF_ORGANIZATION}
       space: ${CF_SPACE}
       url: ${CF_TARGET_URL}
       application: ${CF_APP}
    script: |
      #!/bin/bash
      
      if [ ! -f _generate_deploy_files.sh ]; then
        echo "The _generate_deploy_files.sh is missing. Using the default..."
      else
        echo "Generating deployment files for suffix '$SUFFIX'"
        chmod +x _generate_deploy_files.sh
        ./_generate_deploy_files.sh $SUFFIX || exit 1
        echo "Generated _deploy_create_services.sh"
        cat _deploy_create_services.sh
        echo "--"
        echo "Generated manifest.yml"
        cat manifest.yml
        echo "--"
      fi
      if [[ $CF_TARGET_URL == *".stage1."* ]]; then
        echo "*** Patching manifest.yml to remove IoT4A service in stage1 ***"
        sed -i.bak '/- FleetIoTForAuto/d' ./manifest.yml
        echo "*** Patching manifest.yml to increase memory to 2G ***"
        sed -i 's/memory:.*$/memory: 2G/' ./manifest.yml
        cat manifest.yml
        echo "--"
      fi
      
      # create services
      [ -f "_deploy_create_services.sh" ] && source _deploy_create_services.sh || echo "no create services script"
      cf push "${CF_APP}"
      # View logs
      #cf logs "${CF_APP}" --recent
